// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk659WTImsUyyw5NsuZzXHvWKeQtX_Dk0',
    appId: '1:927828026720:web:bc6bee90dc811f873cea05',
    messagingSenderId: '927828026720',
    projectId: 'ngawasi-45705',
    authDomain: 'ngawasi-45705.firebaseapp.com',
    storageBucket: 'ngawasi-45705.appspot.com',
    measurementId: 'G-LZ6V6FVBJ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvlFKQ8F93wLxFMKkW3GVYR3VCxArAsck',
    appId: '1:927828026720:android:ce4f609acb1d9d2a3cea05',
    messagingSenderId: '927828026720',
    projectId: 'ngawasi-45705',
    storageBucket: 'ngawasi-45705.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT4iNWIUloNnnN052hxkLt7PnV2l9jlDY',
    appId: '1:927828026720:ios:dbca9aa00aff470f3cea05',
    messagingSenderId: '927828026720',
    projectId: 'ngawasi-45705',
    storageBucket: 'ngawasi-45705.appspot.com',
    iosClientId: '927828026720-rlagjgsuu4p02r0a6iql64k3dsceuegr.apps.googleusercontent.com',
    iosBundleId: 'com.example.ngawasi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCT4iNWIUloNnnN052hxkLt7PnV2l9jlDY',
    appId: '1:927828026720:ios:dbca9aa00aff470f3cea05',
    messagingSenderId: '927828026720',
    projectId: 'ngawasi-45705',
    storageBucket: 'ngawasi-45705.appspot.com',
    iosClientId: '927828026720-rlagjgsuu4p02r0a6iql64k3dsceuegr.apps.googleusercontent.com',
    iosBundleId: 'com.example.ngawasi',
  );
}
